name: Go tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run tests
        run: go test -race ./...
